### ISSUE TITLE
Any update on this project?

### ISSUE THREAD

**Issue by JetDexter** [RevEngOps/BMW-E90-Seat-CAN#1]
Hi there,

I too have installed E93 seats into a vintage BMW, and have them programmed with an Arduino to keep-alive. But I am working to find the CAN commands for Heater and memory control. 

I saw you working on this, but it seems you may have hit a dead-end?

Thanks!

**Comment by nagup** [comment]
> Hi there,
> 
> I too have installed E93 seats into a vintage BMW, and have them programmed with an Arduino to keep-alive. But I am working to find the CAN commands for Heater and memory control.
> 
> I saw you working on this, but it seems you may have hit a dead-end?
> 
> Thanks!

Me too, well I am using the seat as an office chair. I even captured the data from the actual car to see what seat heating data appears but when I play the recording back to the seat nothing happens, also doesn't help that for some reason the data doesn't seem to be straight forward like its not a simple message saying level 3,2,1,0. It appears to be changing in a burst of 4 messages in total. Its mind boggling I've tried basically everything I can to be honest.

**Comment by RevEngOps** [comment]
Sorry for the super late reply on this.  I haven't been able to pursue this any further, not to mention the seats I had access to were sold with my buddy's car.
